#! /bin/bash

echo OBSOLETE! >&2
echo "Use ~/Shared/acorg/bin/ad-at-night or ~/Shared/acorg/bin/at-night" >&2
exit 1

# ----------------------------------------------------------------------

export ACMACSD_ROOT=$HOME/AD
PROG=$(readlink -f $0)
LOG=/syn/eu/log/hidb4-night-build.log
DB_DIR=$ACMACSD_ROOT/data

export PATH="$ACMACSD_ROOT/bin:$HOME/bin:/usr/local/bin:$PATH"
export TIME='<Time %E>'

if [ "$(uname)" == "Linux" ]; then
    export LD_LIBRARY_PATH="${ACMACSD_ROOT}/lib:${LD_LIBRARY_PATH}"
fi

on_error()
{
    (echo $PROG FAILED; echo "LOG: /scp:$HOSTNAME:$LOG") | mail -s "$(hostname) $PROG FAILED" eu@antigenic-cartography.org
    exit 1
}

trap on_error ERR

exec > "$LOG"
exec 2>&1

date
echo Updating acmacs-c2
cd ~/ac/acmacs
git pull
c2 make -j11 acmacs

echo "=================================================================="
date
echo Updating ACMACSD packages
# ${ACMACSD_ROOT}/sources/acmacs-build/bin/install-acmacs-d --source ${ACMACSD_ROOT} --target ${ACMACSD_ROOT} --dev-release --acorg-only
cd ${ACMACSD_ROOT}/sources/acmacs-build
git pull
./bin/remake-all TEST=1
install-apache-mod-acmacs
acmacs-api-server-restart

echo "=================================================================="
echo Updating ace-store
whocc-update-ace-store

# echo "=================================================================="
# whocc-hidb4-update

echo "=================================================================="
whocc-hidb5-update

echo "=================================================================="
echo updating reference-antigens-in-tables.csv
WHO_DIR=/syn/WebSites/Protected/who/
TRA_NAME=reference-antigens-in-tables
DATE=$(date +%Y%m%d)
TRA=${WHO_DIR}/${TRA_NAME}.${DATE}.csv
TRA_2018=${WHO_DIR}/${TRA_NAME}.${DATE}.2018.csv
hidb5-reference-antigens-in-tables > "${TRA}"
ln -sf "${TRA}" "${WHO_DIR}/${TRA_NAME}.csv"
hidb5-reference-antigens-in-tables --start 2018 > "${TRA_2018}"
ln -sf "${TRA_2018}" "${WHO_DIR}/${TRA_NAME}.2018.csv"

echo "----------------------------------------------------------------------"

(echo "$PROG completed"; echo "LOG: /scp:$HOSTNAME:$LOG") | mail -s "$(hostname) $PROG completed" eu@antigenic-cartography.org

# ----------------------------------------------------------------------
### Local Variables:
### eval: (if (fboundp 'eu-rename-buffer) (eu-rename-buffer))
### End:
